---
name: E2E tests

on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - '.github/**'

jobs:
  e2e:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile --non-interactive

      - name: Generate missing source files
        run: yarn run typechain

      - name: Run e2e tests
        run: yarn test:e2e
        env:
          RPC_URL: ${{ secrets.RPC_URL }}
          CHAIN_ID: 1
